config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'

  resources :cards, only: %i[index new create]

  namespace :api do
    namespace :v1 do
      resources :transactions, only: %i[create]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, :cpf, :number, :code, :valid_date, :password, presence: true
  validates :number, uniqueness: true
  validates :number, length: { is: 16 }
  validates :cpf, length: { is: 11 }
  validates :password, length: { is: 4 }

  before_validation :generate_password, :generate_number, :generate_code, :generate_valid_date,
                    :set_available_limit, on: :create

  private

  def generate_password
    self.password = SecureRandom.random_number(10**4).to_s.rjust(4, '0')
  end

  def generate_number
    self.number = SecureRandom.random_number(10**16).to_s.rjust(16, '0')
  end

  def generate_code
    self.code = SecureRandom.random_number(10**3).to_s.rjust(3, '0')
  end

  def generate_valid_date
    self.valid_date = 5.years.from_now.to_date
  end

  def set_available_limit
    self.available_limit = total_limit
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  enum status: { accepted: 0, rejected: 5, pending: 9 }

  validates :status, :value, :order, :cpf, :number, presence: true
  validates :value, numericality: { greater_than: 0 }
  validates :order, uniqueness: true

  after_create :checks_and_update_limit

  private

  def checks_and_update_limit
    card = Card.find_by(number:)
    return if valid_date_is_future?(card.valid_date)

    has_limit?(card)
  end

  def valid_date_is_future?(valid_date)
    return unless valid_date < Date.today

    rejected!
  end

  def has_limit?(card)
    if card.available_limit < value
      rejected!
    else
      card.available_limit -= value
      card.save
    end
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  rescue_from ActiveRecord::ActiveRecordError, with: :return500

  private

  def return500
    head 500
  end
end

app/controllers/api/v1/transactions_controller.rb
class Api::V1::TransactionsController < Api::V1::ApiController
  def create
    return render status: 404, json: { errors: 'Cartão invalido, revise os dados' } unless Card.find_by(card_params)

    transaction = Transaction.new(transaction_params)
    if transaction.save
      render status: 201, json: { status: transaction.status,
                                  message: 'Transação realizada com sucesso!' }
    else
      render status: 404, json: { errors: transaction.errors.full_messages }
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:number, :cpf, :value, :order)
  end

  def card_params
    params.require(:transaction).permit(:number, :cpf, :code, :name, :valid_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def new
    @card = Card.new
  end

  def create
    card_params = params.require(:card).permit(:name, :cpf, :total_limit)
    @card = Card.new(card_params)
    if @card.save
      redirect_to root_path, notice: 'Cartão gerado com sucesso'
    else
      flash.now[:notice] = 'Falha ao criar cartão'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registrar-se", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/cards/index.html.erb
<div>
  <% @cards.each do |card| %>
    <p>Nome: <%= card.name %></p>
    <p>CPF: <%= card.cpf %></p>
    <p>Numero: <%= card.number %></p>
    <p>Cod: <%= card.code %></p>
    <p>Validade: <%=l card.valid_date %></p>
    <p>Senha: <%= card.password %></p>
    <p>Limite: <%= card.total_limit %></p>
    <p>Limite disponivel: <%= card.available_limit %></p>
  <% end %>
</div>

app/views/cards/new.html.erb
<section class="container">
  <%= form_with model: @card, html: { class: 'form'} do |f|%>
    <div>
      <div class='field'>
        <%= f.label :name%>
        <%= f.text_field :name %>
        <p class=' text-red-600'><%= @card.errors.full_messages_for(:name).first if @card.errors.any? %></p>
      </div>

      <div class='field'>
        <%= f.label :cpf%>
        <%= f.text_field :cpf %>
        <p class=' text-red-600'><%= @card.errors.full_messages_for(:cpf).first if @card.errors.any? %></p>
      </div>

      <div class='field'>
        <%= f.label :total_limit %>
        <%= f.number_field :total_limit %>
        <p class=' text-red-600'><%= @card.errors.full_messages_for(:total_limit).first if @card.errors.any? %></p>
      </div>

      <div class="w-full">
        <%= f.submit 'Gerar' %>
      </div>
    </div>
  <%end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreditCardsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to 'Cartoes', cards_path %>
        <% if admin_signed_in? %>
          <%= current_admin.email %>
          <%= button_to 'Sair', destroy_admin_session_path, method: 'delete'%>
          <%= link_to 'Gerador de cartão', new_card_path %>
        <% else %>
          <%= link_to 'Entrar', new_admin_session_path, class:'text-green-600 hover:text-green-700' %>
        <% end %>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>